uwsgi:
    env: PYRAMID_SETTINGS=/www/td-odin/development.ini#main
    plugins: python3
    socket: 127.0.0.1:3031
    chdir: /www/td-odin
    wsgi-file: start.py
    # paste: config:/www/td-odin/development.ini
    # callable: application
    master: 1
    worker: 2
    log-slow: true
    touch-reload: /www/restart
